version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
    - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
# Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./EntityFrameworkCore.Convention/EntityFrameworkCore.Convention.csproj --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish ./EntityFrameworkCore.Convention/EntityFrameworkCore.Convention.csproj
after_build:
# For once the build has completed
artifacts:
  - path: 'EntityFrameworkCore.Convention\bin\Debug\netstandard2.0\publish'
    name: dll
    type: zip
clone_depth: 1
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore ./EntityFrameworkCore.Convention.Test/EntityFrameworkCore.Convention.Test.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  - cmd: cd EntityFrameworkCore.Convention.Test
  - cmd: dotnet test
on_finish :
# any cleanup in here
deploy: off